[hostname]
ssh_only = true
ssh_symbol = "🌐"

[aws]
disabled = true

[docker_context]
detect_files = ["Dockerfile"]
detect_folders = []
detect_extensions = []

[dotnet]
disabled = true

[package]
disabled = true

[git_status]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[cmd_duration]
show_notifications = true
min_time_to_notify = 60_000

