[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[dotnet]
disabled = true

[package]
disabled = true

[git_status]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[directory]
truncate_to_repo = false
